language: scala

scala:
  - 2.12.11

jdk:
  - openjdk8

script:
  - sbt "++ ${TRAVIS_SCALA_VERSION}!" test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

deploy:
  # publish from master
  - provider: script
    script: sbt clean publish
    skip_cleanup: true
    on:
      branch: develop
  # publish from tags, aka releases
  - provider: script
    script: sbt clean publish
    skip_cleanup: true
    on:
      tags: true